### ISSUE TITLE
cmd/ev, ui: Can't go get or view docs on godoc.org.

### ISSUE THREAD

**Issue by dmitshur** [gbbr/ev#1]
This project currently has 3 packages:

- [`gbbr.io/ev`](https://godoc.org/gbbr.io/ev)
- [`gbbr.io/ev/cmd/ev`](https://godoc.org/gbbr.io/ev/cmd/ev)
- [`gbbr.io/ev/ui`](https://godoc.org/gbbr.io/ev/ui)

One can only `go get` and view documentation on godoc.org for the first one, but not the other two.

That's because the `go-import` meta tag is served at:

- https://gbbr.io/ev?go-get=1

But not at:

- https://gbbr.io/ev/cmd/ev?go-get=1
- https://gbbr.io/ev/ui?go-get=1

To fix it, it'd be just a matter of serving a valid `go-import` meta tag at those two pages.

The issue is for you to consider making them all work.

**Comment by gbbr** [comment]
I'm not really sure this is needed that much, but if you feel strongly about it, I can add it. I don't really see the value in it. The command is simple enough to use and the public interface is in the root package. The only benefit I see in this is being able to see the godoc for the command (which wouldn't be much) and perhaps being able to `go get gbbr.io/ev/cmd/...`.

I am running [this script](https://github.com/gbbr/junk/blob/master/web-server.go) on my web server and I would have to change it to allow using sub-paths.

I might do it at some point but for now I'll put it aside and leave this issue here.

**Comment by dmitshur** [comment]
I don’t feel very strongly about it, but it is mildly annoying to not be able to go get or view godoc.org for what should be valid Go packages. It also sets a poor example and makes people see vanity import paths in negative light.

> I am running this script on my web server and I would have to change it to allow using sub-paths.

That server looks quite simple and I think fixing the issue would be easy. I can send an updated gist if it’s helpful.

> I might do it at some point but for now I'll put it aside and leave this issue here.

SGTM.

**Comment by gbbr** [comment]
You have a very good point. I will try and address it soon. Thanks a lot for your feedback.
